spring.application.name=industrial-data-server

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:smart-factory}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:password123}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=2000

logging.level.org.hibernate.SQL=debug

# MQTT
app.mqtt.enabled=${APP_MQTT_ENABLED:true}
app.mqtt.broker-url=${APP_MQTT_BROKER_URL:tcp://localhost:1883}
app.mqtt.client-id=${APP_MQTT_CLIENT_ID:industrial-data-server-ingest}
app.mqtt.topics=${APP_MQTT_TOPICS:factory/line1/status}
app.ingestion.default-site-id=${APP_INGESTION_DEFAULT_SITE_ID:SITE-001}
