CREATE TABLE IF NOT EXISTS master_site (
    site_id VARCHAR(40) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS master_asset (
    asset_id VARCHAR(40) PRIMARY KEY,
    site_id VARCHAR(40) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_master_asset_site
        FOREIGN KEY (site_id) REFERENCES master_site(site_id)
);

CREATE TABLE IF NOT EXISTS master_tag (
    tag_id VARCHAR(40) PRIMARY KEY,
    asset_id VARCHAR(40) NOT NULL,
    code VARCHAR(100) NOT NULL,
    data_type VARCHAR(40) NOT NULL,
    unit VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_master_tag_asset
        FOREIGN KEY (asset_id) REFERENCES master_asset(asset_id)
);

CREATE TABLE IF NOT EXISTS telemetry_point (
    telemetry_point_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id VARCHAR(40) NOT NULL,
    asset_id VARCHAR(40),
    device_id VARCHAR(40),
    tag_id VARCHAR(40),
    tag_key VARCHAR(120) NOT NULL,
    value_type VARCHAR(20) NOT NULL,
    value_double NUMERIC(18, 6),
    value_bool BOOLEAN,
    value_text VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_telemetry_site_tag_time UNIQUE (site_id, tag_key, collected_at),
    CONSTRAINT fk_telemetry_site FOREIGN KEY (site_id) REFERENCES master_site(site_id),
    CONSTRAINT fk_telemetry_asset FOREIGN KEY (asset_id) REFERENCES master_asset(asset_id),
    CONSTRAINT fk_telemetry_tag FOREIGN KEY (tag_id) REFERENCES master_tag(tag_id)
);

CREATE INDEX IF NOT EXISTS idx_telemetry_site_tag_time_desc
    ON telemetry_point (site_id, tag_key, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_collected_at
    ON telemetry_point (collected_at);
